### ISSUE TITLE
FrameBuffer pixelformat creating issues after changes in LibGDX 1.9.7?

### ISSUE THREAD

**Issue by Benjamin-Botten** [libgdx/box2dlights#108]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(Lcom/badlogic/gdx/graphics/Pixmap$Format;IIZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(Lcom/badlogic/gdx/graphics/Pixmap$Format;IIZ)V
	at box2dLight.LightMap.<init>(LightMap.java:120)
	at box2dLight.RayHandler.resizeFBO(RayHandler.java:142)
	at box2dLight.RayHandler.<init>(RayHandler.java:131)

**Comment by Benjamin-Botten** [comment]
Updating your gradle build to gdxVersion 1.9.8-SNAPSHOT fixes this particular issue
