### ISSUE TITLE
Potentially broken on GDX 1.9.9

### ISSUE THREAD

**Issue by thechubbypanda** [libgdx/box2dlights#114]
No such method error following getting started guide: 
```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.getColorBufferTexture()Lcom/badlogic/gdx/graphics/Texture;
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at test.Main.main(Main.java:87)
Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.getColorBufferTexture()Lcom/badlogic/gdx/graphics/Texture;
	at box2dLight.LightMap.render(LightMap.java:41)
	at box2dLight.RayHandler.render(RayHandler.java:328)
	at test.Main.render(Main.java:74)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	... 1 more
```

**Comment by thechubbypanda** [comment]
Was using an old version :anguished:
